-- MySQL Script generated by MySQL Workbench
-- 10/29/15 16:25:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `test` ;

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`author` ;

CREATE TABLE IF NOT EXISTS `test`.`author` (
  `id` INT(11) NOT NULL COMMENT '',
  `firstName` VARCHAR(25) NULL DEFAULT NULL COMMENT '',
  `lastName` VARCHAR(25) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`cart` ;

CREATE TABLE IF NOT EXISTS `test`.`cart` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`publisher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`publisher` ;

CREATE TABLE IF NOT EXISTS `test`.`publisher` (
  `id` INT(11) NOT NULL COMMENT '',
  `name` VARCHAR(25) NULL DEFAULT NULL COMMENT '',
  `adress` VARCHAR(25) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`media` ;

CREATE TABLE IF NOT EXISTS `test`.`media` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(25) NOT NULL COMMENT '',
  `price` FLOAT NOT NULL COMMENT '',
  `isbn` VARCHAR(25) NULL DEFAULT NULL COMMENT '',
  `category` INT(11) NULL DEFAULT NULL COMMENT '',
  `dateSortie` DATE NULL DEFAULT NULL COMMENT '',
  `lang` VARCHAR(25) NULL DEFAULT NULL COMMENT '',
  `nbPage` INT(11) NULL DEFAULT NULL COMMENT '',
  `nbTrack` INT(11) NULL DEFAULT NULL COMMENT '',
  `type` INT(11) NOT NULL COMMENT '',
  `id_Publisher` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `isbn` (`isbn` ASC)  COMMENT '',
  INDEX `price` (`price` ASC, `type` ASC)  COMMENT '',
  INDEX `FK_Media_id_Publisher` (`id_Publisher` ASC)  COMMENT '',
  CONSTRAINT `FK_Media_id_Publisher`
    FOREIGN KEY (`id_Publisher`)
    REFERENCES `test`.`publisher` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`cartmedia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`cartmedia` ;

CREATE TABLE IF NOT EXISTS `test`.`cartmedia` (
  `id` INT(11) NOT NULL COMMENT '',
  `id_Media` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `id_Media`)  COMMENT '',
  INDEX `FK_CartMedia_id_Media` (`id_Media` ASC)  COMMENT '',
  CONSTRAINT `FK_CartMedia_id`
    FOREIGN KEY (`id`)
    REFERENCES `test`.`cart` (`id`),
  CONSTRAINT `FK_CartMedia_id_Media`
    FOREIGN KEY (`id_Media`)
    REFERENCES `test`.`media` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`mediaauthor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`mediaauthor` ;

CREATE TABLE IF NOT EXISTS `test`.`mediaauthor` (
  `id` INT(11) NOT NULL COMMENT '',
  `id_Author` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `id_Author`)  COMMENT '',
  INDEX `FK_MediaAuthor_id_Author` (`id_Author` ASC)  COMMENT '',
  CONSTRAINT `FK_MediaAuthor_id`
    FOREIGN KEY (`id`)
    REFERENCES `test`.`media` (`id`),
  CONSTRAINT `FK_MediaAuthor_id_Author`
    FOREIGN KEY (`id_Author`)
    REFERENCES `test`.`author` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`page` ;

CREATE TABLE IF NOT EXISTS `test`.`page` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_Media` INT(11) NULL DEFAULT NULL COMMENT '',
  `texte` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `FK_Page_id_Media` (`id_Media` ASC)  COMMENT '',
  CONSTRAINT `FK_Page_id_Media`
    FOREIGN KEY (`id_Media`)
    REFERENCES `test`.`media` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
